image: busybox:latest

stages:
  - build
  - test
  - deploy
  - stop previous jobs

cache:
  key:
    files:
      - composer.lock
  paths:
    - vendor/

variables:
  IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

include:
  - local: 'local-test.gitlab-ci.yml'
  - remote: 'https://raw.githubusercontent.com/Cos125RUS/CI-CD.IncludeJob/main/github-test.gitlab-ci.yml'

build1:
  stage: build
  script:
    - echo "Do your build here"
    - mkdir -p test
    - echo "<h1>one</h1>" >> file1.txt
    - cp file1.txt test/file1.txt
    - mkdir -p vendor/
    - echo "build" > vendor/hello.txt
  artifacts:
    paths:
      - file1.txt
      - test
    exclude:
      - test/file1.txt
    expire_in: 30 days

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - grep "<h1>one</h1>" file1.txt
    - cat vendor/hello.txt
    # - sleep 60

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
    - grep "<h1>one</h1>" file1.txt

deploy on preprod:
  stage: deploy
  variables:
    MyLogin: PreprodUser
  script:
    - echo "Login is ${MyLogin}"
    - echo "Password is ${MyPassword}"
  only:
    - main
  environment:
    name: preprod

deploy on production:
  stage: deploy
  variables:
    MyLogin: ProdUser
  script:
    - echo "Login is ${MyLogin}"
    - echo "Password is ${MyPassword}"
  only:
    - main
  environment:
    name: production

# cancel:
#   stage: stop previous jobs
#   image: everpeace/curl-jq
#   script:
#     - |
#       if ["$CI_COMMIT_REF_NAME" == "main"]
#         then
#           (
#             echo "Cancel old pipelines from same branch except last"
#             OLD_PIPELINES=$( curl -s -H "PRIVATE-TOKEN: $RUNNER_TOKEN" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipelines?ref=${CI_COMMIT_REF_NAME}&status=running" \
#                   | jq '.[] | .id' | tail -n +2 )
#                   for pipeline in ${OLD_PIPELINES}; \
#                       do echo "Killing ${pipeline}" && \
#                         curl -s --request POST -H "PRIVATE-TOKEN: $RUNNER_TOKEN" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipelines/${pipeline}/cancel"; done
#           ) || echo "Cancel old pipelines (${OLD_PIPELINES}) failrd"   
#       fi